---
version: 2
multicolumn: false
web-width: 500
export-width: 
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - url: "/users/5650/articles/162394/master/file/figures/image1/image1.png"
    path: figures/image1/image1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
